apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-service
  template:
    metadata:
      labels:
        app: metrics-service
    spec:
      containers:
        - name: metrics-service
          image: system-health-platform-metrics-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-service
spec:
  selector:
    app: metrics-service
  ports:
    - port: 5001
      targetPort: 5000
  type: ClusterIP