apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier-service
  template:
    metadata:
      labels:
        app: notifier-service
    spec:
      containers:
        - name: notifier-service
          image: system-health-platform-notifier-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: HEALTH_SERVICE_URL
              value: "http://health-service:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: notifier-service
spec:
  selector:
    app: notifier-service
  ports:
    - port: 5002
      targetPort: 5000
  type: ClusterIP